### ISSUE TITLE
ArgumentError: too long unix socket path (109bytes given but 104bytes max)

### ISSUE THREAD

**Issue by mdayaram** [square/debug_socket#4]
When deploying our app to production, we ran into this error:

```
~/bundle/ruby/2.3.0/gems/debug_socket-0.1.1/lib/debug_socket.rb:23:in `initialize': too long unix socket path (109bytes given but 108bytes max) (ArgumentError)
  from ~/bundle/ruby/2.3.0/gems/debug_socket-0.1.1/lib/debug_socket.rb:23:in `new'
  from ~/bundle/ruby/2.3.0/gems/debug_socket-0.1.1/lib/debug_socket.rb:23:in `start'
  from ~/config/initializers/debug_socket.rb:14:in `<top (required)>'
```

I tried this locally on a Mac OSX, and the limit seemed to be different (104 instead of 108).

**Comment by nerdrew** [comment]
Ya, this is a limitation with unix socket names. I'd recommend using a shorter relative socket name.

cc @zanker @eam

**Comment by nerdrew** [comment]
@mdayaram Did a relative path work for you? Can I close this issue?

**Comment by mdayaram** [comment]
Relative path did not work, though I didn't spend too much time finangling with it.  I ended up just using `Dir.tmp` and calling it a day.  Maybe just add a warning about this error in the README?

**Comment by nerdrew** [comment]
Added tips for this gotcha in the README https://github.com/square/debug_socket/commit/3416e4b0b6218d1dcf874be803ad634e07e5bdf9

**Comment by Juice007** [comment]
https://github.com/CocoaPods/CocoaPods/issues/11640

This works for me
``` shell
git config --global core.fsmonitor false 
```
